"""add_league_tables

Revision ID: 0f7f9b06aa88
Revises: 04fb4d89ffee
Create Date: 2026-06-18 19:21:44.586130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7f9b06aa88'
down_revision: Union[str, Sequence[str], None] = '04fb4d89ffee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('days_played', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_year', 'period_month', name='uq_league_entry')
    )
    op.create_index(op.f('ix_league_entries_user_id'), 'league_entries', ['user_id'], unique=False)
    op.create_table('daily_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'score_date', name='uq_daily_score')
    )
    op.create_index(op.f('ix_daily_scores_score_date'), 'daily_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_daily_scores_user_id'), 'daily_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_scores_user_id'), table_name='daily_scores')
    op.drop_index(op.f('ix_daily_scores_score_date'), table_name='daily_scores')
    op.drop_table('daily_scores')
    op.drop_index(op.f('ix_league_entries_user_id'), table_name='league_entries')
    op.drop_table('league_entries')
    # ### end Alembic commands ###
