"""add_scoreboard_types

Revision ID: 16f74e1a1b51
Revises: 4cd0135979a7
Create Date: 2026-06-23 00:27:54.572319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f74e1a1b51'
down_revision: Union[str, Sequence[str], None] = '4cd0135979a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scoreboard_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scoreboard_types')
    # ### end Alembic commands ###
