"""add_is_bot_to_users

Revision ID: 28244ccbb939
Revises: 0f7f9b06aa88
Create Date: 2026-06-18 20:43:18.738148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28244ccbb939'
down_revision: Union[str, Sequence[str], None] = '0f7f9b06aa88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    # ### end Alembic commands ###
