"""add_league_daily

Revision ID: 3822a6a21dd7
Revises: f1c4acfdbfef
Create Date: 2026-06-24 13:03:29.529677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3822a6a21dd7'
down_revision: Union[str, Sequence[str], None] = 'f1c4acfdbfef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('league_entries', sa.Column('period_day', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_league_entry'), 'league_entries', type_='unique')
    op.create_unique_constraint('uq_league_entry', 'league_entries', ['user_id', 'period_type', 'period_year', 'period_month', 'period_day'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_entry', 'league_entries', type_='unique')
    op.create_unique_constraint(op.f('uq_league_entry'), 'league_entries', ['user_id', 'period_type', 'period_year', 'period_month'], postgresql_nulls_not_distinct=False)
    op.drop_column('league_entries', 'period_day')

    # ### end Alembic commands ###
