"""add_marathon_tables

Revision ID: 6e18765ae81b
Revises: 28244ccbb939
Create Date: 2026-06-18 22:07:24.805147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e18765ae81b'
down_revision: Union[str, Sequence[str], None] = '28244ccbb939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marathons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'starting', 'in_progress', 'finished', name='marathonstatus'), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('questions_per_round', sa.Integer(), nullable=True),
    sa.Column('round_questions', sa.JSON(), nullable=True),
    sa.Column('lobby_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marathons_status'), 'marathons', ['status'], unique=False)
    op.create_table('marathon_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marathon_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.UUID(), nullable=False),
    sa.Column('player2_id', sa.UUID(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marathon_id'], ['marathons.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marathon_matches_marathon_id'), 'marathon_matches', ['marathon_id'], unique=False)
    op.create_table('marathon_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marathon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'eliminated', 'champion', 'second', 'third', name='marathonparticipantstatus'), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('eliminated_at_round', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marathon_id'], ['marathons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marathon_participants_marathon_id'), 'marathon_participants', ['marathon_id'], unique=False)
    op.create_index(op.f('ix_marathon_participants_user_id'), 'marathon_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marathon_participants_user_id'), table_name='marathon_participants')
    op.drop_index(op.f('ix_marathon_participants_marathon_id'), table_name='marathon_participants')
    op.drop_table('marathon_participants')
    op.drop_index(op.f('ix_marathon_matches_marathon_id'), table_name='marathon_matches')
    op.drop_table('marathon_matches')
    op.drop_index(op.f('ix_marathons_status'), table_name='marathons')
    op.drop_table('marathons')
    # ### end Alembic commands ###
