"""match_answer_nullable_match_id

Revision ID: dab88366bea8
Revises: a4684403dc4c
Create Date: 2026-06-22 21:20:47.667414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dab88366bea8'
down_revision: Union[str, Sequence[str], None] = 'a4684403dc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_answers', 'match_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('system_settings', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('match_answers', 'match_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
