"""add_moderation

Revision ID: f1c4acfdbfef
Revises: 6d8d4f5aa3d8
Create Date: 2026-06-23 21:14:47.333583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c4acfdbfef'
down_revision: Union[str, Sequence[str], None] = '6d8d4f5aa3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('moderation_status', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('moderation_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'moderation_reason')
    op.drop_column('events', 'moderation_status')
    # ### end Alembic commands ###
